project_id = "hdpxqqiudiotanrybvcf"

[functions.create-company]
verify_jwt = false

[functions.manage-user]
verify_jwt = false

[functions.evolution-api]
verify_jwt = false

[functions.reservation-events]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.check-whatsapp-status]
verify_jwt = false

[functions.send-post-visit]
verify_jwt = false

[functions.send-birthday-messages]
verify_jwt = false

[functions.expire-waitlist]
verify_jwt = false

[functions.process-message-queue]
verify_jwt = false

[functions.system-health]
verify_jwt = false
